#!/usr/bin/env python3
"""
Check what intents the bot is actually requesting vs what's allowed
"""

import discord

# Create the same intents the bot uses
intents = discord.Intents.default()
intents.voice_states = True
intents.guilds = True

print("=" * 70)
print("Bot Intent Configuration Check")
print("=" * 70)
print()
print(f"Intents value (decimal): {intents.value}")
print(f"Intents value (binary):  {bin(intents.value)}")
print(f"Intents value (hex):     {hex(intents.value)}")
print()
print("Enabled Intents:")
print(f"  guilds: {intents.guilds}")
print(f"  members: {intents.members} {'← PRIVILEGED' if intents.members else ''}")
print(f"  moderation: {intents.moderation}")
print(f"  emojis: {intents.emojis}")
print(f"  integrations: {intents.integrations}")
print(f"  webhooks: {intents.webhooks}")
print(f"  invites: {intents.invites}")
print(f"  voice_states: {intents.voice_states} ← REQUIRED FOR VOICE")
print(f"  presences: {intents.presences} {'← PRIVILEGED' if intents.presences else ''}")
print(f"  messages: {intents.messages}")
print(f"  reactions: {intents.reactions}")
print(f"  typing: {intents.typing}")
print(f"  message_content: {intents.message_content} {'← PRIVILEGED' if intents.message_content else ''}")
print()
print("=" * 70)
print()
print("IMPORTANT NOTES:")
print()
print("1. voice_states is NOT a privileged intent - it should work")
print("   without special enablement in the Developer Portal")
print()
print("2. Error 4006 with voice connections usually indicates:")
print("   a) A session management issue in py-cord")
print("   b) Network/firewall blocking UDP voice traffic")
print("   c) Discord voice endpoint incompatibility")
print("   d) Rarely: Intent mismatch (but voice_states isn't privileged)")
print()
print("3. Since your Gateway connection works (bot connects successfully),")
print("   the issue is likely with the VOICE GATEWAY specifically")
print()
print("=" * 70)
print()
print("Discord Intent Bits Reference:")
print("  GUILDS (1 << 0) = 1")
print("  GUILD_MEMBERS (1 << 1) = 2 [PRIVILEGED]")
print("  GUILD_MODERATION (1 << 2) = 4")
print("  GUILD_EMOJIS (1 << 3) = 8")
print("  GUILD_INTEGRATIONS (1 << 4) = 16")
print("  GUILD_WEBHOOKS (1 << 5) = 32")
print("  GUILD_INVITES (1 << 6) = 64")
print("  GUILD_VOICE_STATES (1 << 7) = 128 ← VOICE CONNECTIONS")
print("  GUILD_PRESENCES (1 << 8) = 256 [PRIVILEGED]")
print("  GUILD_MESSAGES (1 << 9) = 512")
print("  GUILD_MESSAGE_REACTIONS (1 << 10) = 1024")
print("  GUILD_MESSAGE_TYPING (1 << 11) = 2048")
print("  DM_MESSAGES (1 << 12) = 4096")
print("  DM_MESSAGE_REACTIONS (1 << 13) = 8192")
print("  DM_MESSAGE_TYPING (1 << 14) = 16384")
print("  MESSAGE_CONTENT (1 << 15) = 32768 [PRIVILEGED]")
print()
print(f"Your bot's intent value {intents.value} includes:")
for i in range(32):
    if intents.value & (1 << i):
        print(f"  Bit {i}: {1 << i}")
print()
